### ISSUE TITLE
Eu recomendo que você crie uma nova pasta para os arquivos css, pois seria mais gerenciável

### ISSUE THREAD

**Issue by kumartul** [iuricode/portfolio#10]
Você pode simplesmente alterar o caminho de compilação do Live Sass Compiler clicando no ícone de engrenagem na barra lateral do VS Code e em Configurações. Pesquise Live Sass e clique em Configurações: Formatos e simplesmente em settings.json, adicione este pedaço de código:

`"liveSassCompile.settings.formats": [`
`    {`
`        "format": "expanded",`
`        "extensionName": ".css",`
`        "savePath": "/portfolio/assets/css/"`
`    }`
`]`

Agora você está pronto para ir

**Comment by iuricode** [comment]
Muito obrigado pela sugestão, irei usar ela com toda certeza!

**Comment by kumartul** [comment]
Estou feliz que você gostou :)
