### ISSUE TITLE
Oferecimento de ajuda para envio de e-mail com PHP e Ajax

### ISSUE THREAD

**Issue by afaferz** [iuricode/portfolio#4]
Boa tarde Iuri! Acabo de conhecer seu projeto de portfólio por acaso no GitHub e fiquei maravilhado com seu talento. Estou criando um 'curriculo' para mim também e revisando códigos de vários sites para ver o que consigo tirar de inspiração :D 

Eu adorei a sua ideia de preenchimento das estrelas com a largura e o seu nível de experiência, parabéns!

Mas vim aqui te oferecer ajuda para que consiga enviar um e-mail na sua sessão contatos sem utilizar o 'mail:to' mas sim com Ajax e PHP (não sei se tem conhecimento neste assunto, mas creio que ja tenha visto com certeza). Eu estava com esse problema de envio de email e desenvolvi um código simples com o que consegui recolher de conhecimento e se quiser posso passar para ti :D Vi que aceita colaborações no projeto, queria mandar essa 'issue' antes para depois poder solicitar o pull request

**Comment by iuricode** [comment]
Olá afafez tudo bem contigo irmão? Muito obrigado pelo feedback. 

Eu sou desenvolvedor Front-end então, nessa parte de php não sou bom. Claro que eu consigo pegar código sobre formulário em php na web porém, acho que seria legal eu entender sobre o código né?!

Aceito seu pull request com toda certeza! Se puder deixar um comentário bacana (como esse) no PR eu agradeço, meio só falando sobre o código que você fez. 

Muito obrigado pelo contato afaferz, estou na espera do seu PR!!
