### ISSUE TITLE
Os elementos do footer estão sobrepondo o botão de scrollTop, impossibilitando o clique.

### ISSUE THREAD

**Issue by gabrielkuhn** [iuricode/portfolio#8]
Olá Iuri! Tudo certo?

Percebi que tanto o `<p>` quando o `<article>`  do footer estão ficando por cima do botão de voltar ao topo. 
Dessa forma, quando o scroll está no final da página, apenas metade do botão fica clicável.

![err](https://user-images.githubusercontent.com/67128059/116342211-9d4fb600-a7b8-11eb-9cc2-cabfed1763bd.JPG)

Qualquer dúvida estou à disposição. 
Lindo portfolio btw 🚀 ✨

**Comment by iuricode** [comment]
Muito obrigado Gabriel, me ajudou muito com esse feedback!
